version: '2'
services:
  redis.server:
    image: redis
    ports:
      - 6974:6379/tcp

  promethrus:
    image: prom/prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - $GOPATH/src/surls/docker/prometheus/data:/prometheus-data
    command: --config.file=/prometheus-data/prometheus.yml

  surls:
    image: golang:1.10.2-alpine
    ports:
      - 7070:7070/tcp
      - 7071:7071/tcp
      - 7072:7072/tcp
      - 7073:7073/tcp
      - 7074:7074/tcp
    links:
      - redis.server
    depends_on:
      - redis.server
    volumes:
      - $GOPATH/src/surls:/go/src/surls
    entrypoint:
      - ash
      - -c
      - |
        sleep 1 && \
        cd /go/src/surls && \
        ./bin/surls_linux_amd64 --run-mode container

