// Code generated by protoc-gen-go. DO NOT EDIT.
// source: surls.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetReq struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_surls_b7ccc3071e22dffb, []int{0}
}
func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (dst *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(dst, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_surls_b7ccc3071e22dffb, []int{1}
}
func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (dst *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(dst, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SetReq struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReq) Reset()         { *m = SetReq{} }
func (m *SetReq) String() string { return proto.CompactTextString(m) }
func (*SetReq) ProtoMessage()    {}
func (*SetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_surls_b7ccc3071e22dffb, []int{2}
}
func (m *SetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReq.Unmarshal(m, b)
}
func (m *SetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReq.Marshal(b, m, deterministic)
}
func (dst *SetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReq.Merge(dst, src)
}
func (m *SetReq) XXX_Size() int {
	return xxx_messageInfo_SetReq.Size(m)
}
func (m *SetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetReq proto.InternalMessageInfo

func (m *SetReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type SetResp struct {
	Code                 int32        `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data                 *SetRespData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetResp) Reset()         { *m = SetResp{} }
func (m *SetResp) String() string { return proto.CompactTextString(m) }
func (*SetResp) ProtoMessage()    {}
func (*SetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_surls_b7ccc3071e22dffb, []int{3}
}
func (m *SetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResp.Unmarshal(m, b)
}
func (m *SetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResp.Marshal(b, m, deterministic)
}
func (dst *SetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResp.Merge(dst, src)
}
func (m *SetResp) XXX_Size() int {
	return xxx_messageInfo_SetResp.Size(m)
}
func (m *SetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetResp proto.InternalMessageInfo

func (m *SetResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SetResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SetResp) GetData() *SetRespData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SetRespData struct {
	SourceUrl            string   `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl" json:"source_url,omitempty"`
	ShortUrl             string   `protobuf:"bytes,2,opt,name=short_url,json=shortUrl" json:"short_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRespData) Reset()         { *m = SetRespData{} }
func (m *SetRespData) String() string { return proto.CompactTextString(m) }
func (*SetRespData) ProtoMessage()    {}
func (*SetRespData) Descriptor() ([]byte, []int) {
	return fileDescriptor_surls_b7ccc3071e22dffb, []int{4}
}
func (m *SetRespData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRespData.Unmarshal(m, b)
}
func (m *SetRespData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRespData.Marshal(b, m, deterministic)
}
func (dst *SetRespData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRespData.Merge(dst, src)
}
func (m *SetRespData) XXX_Size() int {
	return xxx_messageInfo_SetRespData.Size(m)
}
func (m *SetRespData) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRespData.DiscardUnknown(m)
}

var xxx_messageInfo_SetRespData proto.InternalMessageInfo

func (m *SetRespData) GetSourceUrl() string {
	if m != nil {
		return m.SourceUrl
	}
	return ""
}

func (m *SetRespData) GetShortUrl() string {
	if m != nil {
		return m.ShortUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*GetReq)(nil), "pb.GetReq")
	proto.RegisterType((*GetResp)(nil), "pb.GetResp")
	proto.RegisterType((*SetReq)(nil), "pb.SetReq")
	proto.RegisterType((*SetResp)(nil), "pb.SetResp")
	proto.RegisterType((*SetRespData)(nil), "pb.SetRespData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SUrlsClient is the client API for SUrls service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SUrlsClient interface {
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error)
	Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetResp, error)
}

type sUrlsClient struct {
	cc *grpc.ClientConn
}

func NewSUrlsClient(cc *grpc.ClientConn) SUrlsClient {
	return &sUrlsClient{cc}
}

func (c *sUrlsClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	out := new(GetResp)
	err := c.cc.Invoke(ctx, "/pb.SUrls/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sUrlsClient) Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetResp, error) {
	out := new(SetResp)
	err := c.cc.Invoke(ctx, "/pb.SUrls/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SUrlsServer is the server API for SUrls service.
type SUrlsServer interface {
	Get(context.Context, *GetReq) (*GetResp, error)
	Set(context.Context, *SetReq) (*SetResp, error)
}

func RegisterSUrlsServer(s *grpc.Server, srv SUrlsServer) {
	s.RegisterService(&_SUrls_serviceDesc, srv)
}

func _SUrls_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SUrlsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SUrls/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SUrlsServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SUrls_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SUrlsServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SUrls/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SUrlsServer).Set(ctx, req.(*SetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SUrls_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SUrls",
	HandlerType: (*SUrlsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SUrls_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _SUrls_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "surls.proto",
}

func init() { proto.RegisterFile("surls.proto", fileDescriptor_surls_b7ccc3071e22dffb) }

var fileDescriptor_surls_b7ccc3071e22dffb = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x62, 0x5b, 0x33, 0x41, 0x2a, 0x03, 0x42, 0x88, 0x0a, 0x12, 0x2f, 0xe2, 0x21,
	0xc1, 0x8a, 0x20, 0x5e, 0x15, 0x8a, 0xd7, 0xc4, 0x9c, 0x65, 0xd3, 0x2e, 0xb1, 0xb0, 0xcd, 0xae,
	0xbb, 0x1b, 0xf1, 0xec, 0x2b, 0xf8, 0x68, 0xbe, 0x82, 0x0f, 0x22, 0x3b, 0x89, 0x9a, 0x8b, 0x07,
	0x6f, 0x3f, 0xff, 0xcc, 0x97, 0x2f, 0xcc, 0x42, 0x64, 0x3a, 0x2d, 0x4c, 0xa6, 0xb4, 0xb4, 0x12,
	0x7d, 0x55, 0x27, 0x47, 0x8d, 0x94, 0x8d, 0xe0, 0x39, 0x53, 0x9b, 0x9c, 0xb5, 0xad, 0xb4, 0xcc,
	0x6e, 0x64, 0x3b, 0x6c, 0xa4, 0x09, 0x4c, 0x97, 0xdc, 0x16, 0xfc, 0x19, 0xf7, 0x21, 0xe8, 0xb4,
	0x88, 0xbd, 0x13, 0xef, 0x2c, 0x2c, 0x5c, 0x4c, 0x6f, 0x61, 0x46, 0x33, 0xa3, 0x10, 0x61, 0x67,
	0x25, 0xd7, 0x9c, 0xa6, 0x93, 0x82, 0xb2, 0x03, 0xb6, 0xa6, 0x89, 0xfd, 0x1e, 0xd8, 0x9a, 0xc6,
	0x6d, 0xad, 0x99, 0x65, 0x71, 0x40, 0x15, 0x65, 0x27, 0x28, 0xff, 0x12, 0x3c, 0xc0, 0xac, 0xfc,
	0x97, 0xe0, 0x74, 0x24, 0x88, 0x16, 0xf3, 0x4c, 0xd5, 0xd9, 0xf0, 0x81, 0x3b, 0x66, 0xd9, 0x60,
	0xbc, 0x87, 0x68, 0x54, 0xe2, 0x31, 0x80, 0x91, 0x9d, 0x5e, 0xf1, 0xc7, 0x5f, 0x7b, 0xd8, 0x37,
	0x95, 0x16, 0x78, 0x08, 0xa1, 0x79, 0x92, 0xda, 0xd2, 0xb4, 0x57, 0xed, 0x52, 0x51, 0x69, 0xb1,
	0x78, 0x85, 0x49, 0x59, 0x69, 0x61, 0xf0, 0x0a, 0x82, 0x25, 0xb7, 0x08, 0xce, 0xd8, 0xdf, 0x2b,
	0x89, 0x7e, 0xb2, 0x51, 0xe9, 0xc1, 0xdb, 0xc7, 0xe7, 0xbb, 0x3f, 0xc7, 0xbd, 0x9c, 0xce, 0x9f,
	0xbf, 0x5c, 0xe4, 0x0d, 0xb7, 0x78, 0x0d, 0x41, 0xf9, 0x8d, 0x95, 0x23, 0x6c, 0xf8, 0xbf, 0x34,
	0x26, 0x0c, 0xd3, 0x11, 0x66, 0xb8, 0xbd, 0xf1, 0xce, 0xeb, 0x29, 0x3d, 0xcf, 0xe5, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd0, 0x0d, 0x17, 0xbd, 0xcf, 0x01, 0x00, 0x00,
}
